### ISSUE TITLE
icd: crash in intel_dev_log()

### ISSUE THREAD

**Issue by Jajcus** [LunarG/VulkanTools#10]
From backtrace of my (buggy) application:

```
(gdb) bt
#0  intel_dev_log (dev=dev@entry=0x625740, msg_flags=msg_flags@entry=8, src_object=src_object@entry=0x0, location=location@entry=0, msg_code=msg_code@entry=0, 
    format=format@entry=0x7ffff75283e0 "invalid presentable image format") at /usr/src/debug/vulkan-sdk-1.0.3.0/VulkanTools/icd/intel/dev.c:206
#1  0x00007ffff6ee02a8 in x11_swap_chain_create (sc_ret=0x7fffec1fdee8, info=0x7fffec1fde40, dev=0x625740)
    at /usr/src/debug/vulkan-sdk-1.0.3.0/VulkanTools/icd/intel/wsi_x11.c:887
#2  vkCreateSwapchainKHR (device=0x625740, pCreateInfo=0x7fffec1fde40, pAllocator=<optimized out>, pSwapchain=0x7fffec1fdee8)
    at /usr/src/debug/vulkan-sdk-1.0.3.0/VulkanTools/icd/intel/wsi_x11.c:1204
[...]
(gdb) list
201	{
202	    va_list ap;
203	
204	    va_start(ap, format);
205	    intel_logv(dev, msg_flags,
206	               (src_object->dbg ? src_object->dbg->type : 0),
207	               (uint64_t) src_object,
208	               location, msg_code,
209	               format, ap);
210	    va_end(ap);
(gdb) up
#1  0x00007ffff6ee02a8 in x11_swap_chain_create (sc_ret=0x7fffec1fdee8, info=0x7fffec1fde40, dev=0x625740)
    at /usr/src/debug/vulkan-sdk-1.0.3.0/VulkanTools/icd/intel/wsi_x11.c:887
887	        intel_dev_log(dev, VK_DEBUG_REPORT_ERROR_BIT_EXT,
(gdb) list
882	    struct intel_x11_swap_chain *sc;
883	    int fd;
884	
885	    /* TODOVV: Add test to validation layer */
886	    if (!x11_is_format_presentable(dev, info->imageFormat)) {
887	        intel_dev_log(dev, VK_DEBUG_REPORT_ERROR_BIT_EXT,
888	                      VK_NULL_HANDLE, 0, 0, "invalid presentable image format");
889	//        return VK_ERROR_INVALID_VALUE;
890	        return VK_ERROR_VALIDATION_FAILED_EXT;
891	    }
```

`intel_dev_log` is called with `src_object= VK_NULL_HANDLE`, but then it is dereferenced with `src_object->dbg`.

**Comment by karl-lunarg** [comment]
Fixed this and one other instance of the same problem.  Pushed to master.
