### ISSUE TITLE
Crash on Wayland with VK_LAYER_LUNARG_monitor actived

### ISSUE THREAD

**Issue by Arthapz** [LunarG/VulkanTools#1409]
Hi,
when i enable VK_LAYER_LUNARG_monitor with my wayland backend, it crash with this backtrace

```
#0  0x00007ffff0652144 in xcb_send_request_with_fds64 () from /usr/lib/libxcb.so.1
#1  0x00007ffff06526ba in xcb_send_request () from /usr/lib/libxcb.so.1
#2  0x00007ffff0659303 in xcb_change_property () from /usr/lib/libxcb.so.1
#3  0x00007fffe747d414 in vkQueuePresentKHR () from /usr/lib/libVkLayer_monitor.so
#4  0x00007fffe73df152 in ?? () from /usr/lib/libVkLayer_MESA_overlay.so
#5  0x00007fffe66b3f63 in DispatchQueuePresentKHR (queue=0x55555651d2b0, pPresentInfo=0x7fffffffe2a0) at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-1.2.172/layers/generated/vk_safe_struct.h:3174
#6  0x00007fffe664dc41 in vulkan_layer_chassis::QueuePresentKHR (queue=0x55555651d2b0, pPresentInfo=0x7fffffffe2a0) at /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-1.2.172/layers/generated/chassis.cpp:4883
#7  0x0000555555676c0d in vk::Queue::presentKHR<vk::DispatchLoaderDynamic> (d=..., presentInfo=..., this=0x555556430090) at /usr/include/vulkan/vulkan.hpp:92863
#8  storm::render::Queue::vkPresent (this=0x555556430080, present_info=...) at ../../../repos/stormkit/render/src/core/Queue.cpp:168
#9  0x0000555555667f8d in storm::render::WindowSurface::present (this=0x555555f002b0, frame=...) at ../../../repos/stormkit/render/src/core/WindowSurface.cpp:192
#10 0x00005555555ad139 in App::run (this=0x7fffffffe450, argc=1, argv=0x7fffffffe5e8) at ../../../repos/stormkit/render/samples/Triangle/src/App.cpp:76
#11 0x000055555557ddb3 in main (argc=1, argv=0x7fffffffe5e8) at ../../../repos/stormkit/render/samples/Triangle/src/main.cpp:13
```

**Comment by Tony-LunarG** [comment]
It looks like it crashes with VK_LAYER_MESA_overlay too.  Both use xcb to communicate with the X server. Are you sure that your xcb configuration is correct?  Are there other apps that use xcb that run successfully on your system?  Does the VK_LAYER_LUNARG_monitor stack trace look like the VK_LAYER_MESA_overlay stack trace above?

**Comment by Arthapz** [comment]
When i disable VK_LAYER_LUNARG_monitor, i don't have any crash, VK_LAYER_MESA_overlay is working fine, other xcb app run fine too.
