### ISSUE TITLE
vkconfig: aborts when a vulkan sdk is not found

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1443]
When no SDK is installed, either the Ubuntu packages or the environment is not set using the tar ball, vkconfig aborts abruptly. Should a message be shown to explain that the vulkan sdk or appropriate vulkan components could not be found?

```
lunarg@helium:~/VulkanTools/dbuild/vkconfig$ ./vkconfig
vkconfig: /home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp:60: void ConfigurationManager::LoadDefaultConfigurations(const std::vector<Layer>&): Assertion `result' failed.
Aborted (core dumped)

lunarg@helium:~/VulkanTools/dbuild/vkconfig$ gdb vkconfig
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vkconfig...
(gdb) r
Starting program: /home/lunarg/VulkanTools/dbuild/vkconfig/vkconfig 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2da1700 (LWP 8688)]
[New Thread 0x7ffff1206700 (LWP 8689)]
[New Thread 0x7ffff0a05700 (LWP 8690)]
[New Thread 0x7fffe3efe700 (LWP 8691)]
vkconfig: /home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp:60: void ConfigurationManager::LoadDefaultConfigurations(const std::vector<Layer>&): Assertion `result' failed.

Thread 1 "vkconfig" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6706859 in __GI_abort () at abort.c:79
#2  0x00007ffff6706729 in __assert_fail_base (fmt=0x7ffff689c588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555557a74c9 "result", 
    file=0x5555557a7488 "/home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp", line=60, function=<optimized out>) at assert.c:92
#3  0x00007ffff6717f36 in __GI___assert_fail (assertion=0x5555557a74c9 "result", 
    file=0x5555557a7488 "/home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp", line=60, 
    function=0x5555557a7438 "void ConfigurationManager::LoadDefaultConfigurations(const std::vector<Layer>&)") at assert.c:101
#4  0x00005555555d90cc in ConfigurationManager::LoadDefaultConfigurations (this=0x555555818f08 <Configurator::Get()::configurator+712>, 
    available_layers=std::vector of length 8, capacity 10 = {...}) at /home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp:60
#5  0x00005555555d8f45 in ConfigurationManager::LoadAllConfigurations (this=0x555555818f08 <Configurator::Get()::configurator+712>, 
    available_layers=std::vector of length 8, capacity 10 = {...}) at /home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp:42
#6  0x00005555555da7ec in ConfigurationManager::ResetDefaultsConfigurations (this=0x555555818f08 <Configurator::Get()::configurator+712>, 
    available_layers=std::vector of length 8, capacity 10 = {...}) at /home/lunarg/VulkanTools/vkconfig_core/configuration_manager.cpp:288
#7  0x0000555555581a61 in Configurator::Init (this=0x555555818c40 <Configurator::Get()::configurator>)
    at /home/lunarg/VulkanTools/vkconfig/configurator.cpp:113
#8  0x00005555555a099c in run_gui (argc=1, argv=0x7fffffffe0a8) at /home/lunarg/VulkanTools/vkconfig/main_gui.cpp:71
#9  0x00005555555a0654 in main (argc=1, argv=0x7fffffffe0a8) at /home/lunarg/VulkanTools/vkconfig/main.cpp:57
```

**Comment by johnzupin** [comment]
Fixed using ref: v1.2.170-261-g5aeab5532
