### ISSUE TITLE
vulkaninfo segfaults

### ISSUE THREAD

**Issue by birdspider** [LunarG/VulkanTools#1624]
AFAIK, since I upgraded vulkan-tools on archlinux today*, `vulkaninfo` with no params segfaults,  `vulkaninfo --summary`  does not.

*) [2021-11-25T17:10:32+0100] [ALPM] upgraded vulkan-tools (1.2.194-1 -> 1.2.199-1)

I rebuild them myself, the segfault persisted.

Can I provide more info? 

---

bt of debug build

```
Thread 1 "vulkaninfo" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555555d289c in GetVectorInit<VkPhysicalDeviceToolPropertiesEXT, VkResult (*&)(VkPhysicalDevice_T*, unsigned int*, VkPhysicalDeviceToolPropertiesEXT*), VkPhysicalDevice_T*&> (
    func_name=func_name@entry=0x5555555e0648 "vkGetPhysicalDeviceToolPropertiesEXT", f=@0x7fffffffd4c0: 0x7ffff7853850, init=...)
    at /usr/src/debug/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.h:247
#2  0x00005555555b3944 in GetVector<VkPhysicalDeviceToolPropertiesEXT, VkResult (*&)(VkPhysicalDevice_T*, unsigned int*, VkPhysicalDeviceToolPropertiesEXT*), VkPhysicalDevice_T*&> (
    f=@0x7fffffffd4c0: 0x7ffff7853850, func_name=0x5555555e0648 "vkGetPhysicalDeviceToolPropertiesEXT") at /usr/src/debug/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.h:259
#3  GetToolingInfo (gpu=...) at /usr/src/debug/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.h:1717
#4  GpuDumpToolingInfo (p=..., gpu=...) at /usr/src/debug/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.cpp:559
#5  0x00005555555b5578 in DumpGpu (p=..., gpu=..., show_formats=<optimized out>) at /usr/src/debug/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.cpp:661
#6  0x000055555556adf8 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/11.1.0/bits/unique_ptr.h:173
```

**Comment by birdspider** [comment]
wait - wrong repo
