### ISSUE TITLE
SPIRV-Tools-master-linux-RelWithDebInfo.zip not exist in VulkanSamples cause build error

### ISSUE THREAD

**Issue by xuewenwang** [LunarG/VulkanTools#1663]
how to slove this error?

VulkanSamples/API-Samples/android$python3 ./compile_shaders.py
SPIRV_TOOLS_FILENAME= SPIRV-Tools-master-linux-RelWithDebInfo.zip SPIRV_TOOLS_COMPLETE_URL= https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip
   Downloading spirv-as binary from spirv-tools releases dir
Traceback (most recent call last):
  File "../../scripts/fetch_spirv_tools.py", line 65, in <module>
    with urllib.request.urlopen(SPIRV_TOOLS_COMPLETE_URL, context=ssl._create_unverified_context()) as response, open(SPIRV_TOOLS_OUTFILENAME, 'wb') as out_file:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./compile_shaders.py", line 21, in <module>
    subprocess.check_call(args)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '../../scripts/fetch_spirv_tools.py', 'SPIRV-Tools-master-linux-RelWithDebInfo.zip']' returned non-zero exit status 1.

**Comment by KarenGhavam-lunarG** [comment]
This repository is not the place for an issue with building LunarG/VulkanSamples. In addition, the VulkanSamples repository was archived quite some time ago and is no longer maintained, supported, enhanced.

**Comment by KarenGhavam-lunarG** [comment]
> Please remove it from the official website of anrdoid about vulkan.
https://developer.android.google.cn/ndk/guides/graphics/getting-started

We don't have any ownership or control over Google's Android website. We have contacted them in the past to tell them about this. Will do so again. But can't guarantee results.
