### ISSUE TITLE
vktrace signal handler corrupts memory as it calls unsafe functions

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#169]
Saw following in Valgrind output:
```
testfw_app: vktrace/vktrace_common/vktrace_trace_packet_utils.c:188: vktrace_add_buffer_to_trace_packet: Assertion `(size&0x3) == 0' failed.
vktrace info: vktrace_lib library handle signal 6.
==10119== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==10119==    at 0x5FBE9FF: send (send.c:26)
==10119==    by 0xB223BE5: vktrace_MessageStream_ReallySend (vktrace_interconnect.c:393)
==10119==    by 0xB223BE5: vktrace_MessageStream_BufferedSend (vktrace_interconnect.c:358)
==10119==    by 0xB223BE5: vktrace_MessageStream_Send (vktrace_interconnect.c:382)
==10119==    by 0xB225619: vktrace_write_trace_packet (vktrace_trace_packet_utils.c:235)
==10119==    by 0xB2036F7: loggingCallback (vktrace_lib.c:105)
==10119==    by 0xB224C5E: LogGuts (vktrace_tracelog.c:143)
==10119==    by 0xB225085: vktrace_LogVerbose (vktrace_tracelog.c:208)
==10119==    by 0xB2037CA: vktrace_sighandler (vktrace_lib.c:68)
==10119==    by 0x5FBF38F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.23.so)
==10119==    by 0x7174427: raise (raise.c:54)
==10119==    by 0x7176029: abort (abort.c:89)
==10119==    by 0x716CBD6: __assert_fail_base (assert.c:92)
==10119==    by 0x716CC81: __assert_fail (assert.c:101)
==10119==    by 0xB225477: vktrace_add_buffer_to_trace_packet (vktrace_trace_packet_utils.c:188)
==10119==    by 0xB20708C: vkFlushMappedMemoryRangesWithoutAPICall(VkDevice_T*, unsigned int, VkMappedMemoryRange const*) (vktrace_lib_pageguard.cpp:400)
==10119==    by 0xB2068FC: flushTargetChangedMappedMemory(PageGuardMappedMemory*, VkResult (*)(VkDevice_T*, unsigned int, VkMappedMemoryRange const*), VkMappedMemoryRange*) (vktrace_lib_pageguard.cpp:248)
==10119==    by 0xB204C77: PageGuardCapture::vkUnmapMemoryPageGuardHandle(VkDevice_T*, VkDeviceMemory_T*, void**, VkResult (*)(VkDevice_T*, unsigned int, VkMappedMemoryRange const*)) (vktrace_lib_pageguardcapture.cpp:84)
==10119==
==10119==  Address 0x1501cf85 is 133 bytes inside a block of size 136 alloc'd
==10119==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10119==    by 0xB225283: vktrace_malloc (vktrace_memory.h:39)
==10119==    by 0xB225283: vktrace_create_trace_packet (vktrace_trace_packet_utils.c:132)
==10119==    by 0xB203690: loggingCallback (vktrace_lib.c:95)
==10119==    by 0xB224C5E: LogGuts (vktrace_tracelog.c:143)
==10119==    by 0xB225085: vktrace_LogVerbose (vktrace_tracelog.c:208)
==10119==    by 0xB2037CA: vktrace_sighandler (vktrace_lib.c:68)
==10119==    by 0x5FBF38F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.23.so)
==10119==    by 0x7174427: raise (raise.c:54)
==10119==    by 0x7176029: abort (abort.c:89)
==10119==    by 0x716CBD6: __assert_fail_base (assert.c:92)
==10119==    by 0x716CC81: __assert_fail (assert.c:101)
==10119==    by 0xB225477: vktrace_add_buffer_to_trace_packet (vktrace_trace_packet_utils.c:188)
==10119==    by 0xB20708C: vkFlushMappedMemoryRangesWithoutAPICall(VkDevice_T*, unsigned int, VkMappedMemoryRange const*) (vktrace_lib_pageguard.cpp:400)
==10119==    by 0xB2068FC: flushTargetChangedMappedMemory(PageGuardMappedMemory*, VkResult (*)(VkDevice_T*, unsigned int, VkMappedMemoryRange const*), VkMappedMemoryRange*) (vktrace_lib_pageguard.cpp:248)
==10119==    by 0xB204C77: PageGuardCapture::vkUnmapMemoryPageGuardHandle(VkDevice_T*, VkDeviceMemory_T*, void**, VkResult (*)(VkDevice_T*, unsigned int, VkMappedMemoryRange const*)) (vktrace_lib_pageguardcapture.cpp:84)
==10119==    by 0xB217AC5: __HOOKED_vkUnmapMemory (vktrace_lib_trace.cpp:449)
```

Calling anything that even potentially does allocations/frees from signal handler is broken.  Doing so will eventually cause libc memory allocation book keeping to get corrupted.  Signal context is asynchronous to rest of the program, but *with no support for locking*.  "man 7 signal" lists the only functions that are safe to call from signal context, even indirectly.

Note: besides the logging callback, there are several unsafe functions that are called directly from LogGuts().

Normally signal handlers set just some variable or write to pipe that informs the mainloop about it, or if that's not possible, people write their own signal-context-safe logging functions.

Assert itself is:
```
testfw_app: vktrace/vktrace_common/vktrace_trace_packet_utils.c:188: vktrace_add_buffer_to_trace_packet: Assertion `(size&0x3) == 0' failed.

Thread 2 "testfw_app" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff363f700 (LWP 10309)]
0x00007ffff573e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff573e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff574002a in __GI_abort () at abort.c:89
#2  0x00007ffff5736bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff200ab5f "(size&0x3) == 0", 
    file=file@entry=0x7ffff200aa00 "vktrace/vktrace_common/vktrace_trace_packet_utils.c", line=line@entry=188, 
    function=function@entry=0x7ffff200abc0 <__PRETTY_FUNCTION__.19275> "vktrace_add_buffer_to_trace_packet") at assert.c:92
#3  0x00007ffff5736c82 in __GI___assert_fail (assertion=assertion@entry=0x7ffff200ab5f "(size&0x3) == 0", 
    file=file@entry=0x7ffff200aa00 "vktrace/vktrace_common/vktrace_trace_packet_utils.c", line=line@entry=188, 
    function=function@entry=0x7ffff200abc0 <__PRETTY_FUNCTION__.19275> "vktrace_add_buffer_to_trace_packet") at assert.c:101
#4  0x00007ffff2006478 in vktrace_add_buffer_to_trace_packet (pHeader=<optimized out>, ptr_address=<optimized out>, size=<optimized out>, 
    pBuffer=<optimized out>) at vktrace/vktrace_common/vktrace_trace_packet_utils.c:188
#5  0x00007ffff1fe808d in vkFlushMappedMemoryRangesWithoutAPICall (device=0x7fffec265380, memoryRangeCount=<optimized out>, 
    pMemoryRanges=<optimized out>) at vktrace/vktrace_layer/vktrace_lib_pageguard.cpp:400
#6  0x00007ffff1fe78fd in flushTargetChangedMappedMemory (TargetMappedMemory=0x7fffeca8ec50, 
    pFunc=0x7ffff1fe7cc0 <vkFlushMappedMemoryRangesWithoutAPICall(VkDevice_T*, unsigned int, VkMappedMemoryRange const*)>, 
    pMemoryRanges=0x7ffff363df80) at vktrace/vktrace_layer/vktrace_lib_pageguard.cpp:248
#7  0x00007ffff1fe5c78 in PageGuardCapture::vkUnmapMemoryPageGuardHandle (this=0x7ffff22133a0 <getPageGuardControlInstance()::OPTControl>, 
    device=device@entry=0x7fffec265380, memory=memory@entry=0x7fffecb33580, MappedData=MappedData@entry=0x7ffff363e010, pFunc=<optimized out>)
    at vktrace/vktrace_layer/vktrace_lib_pageguardcapture.cpp:84
#8  0x00007ffff1ff8ac6 in __HOOKED_vkUnmapMemory (device=0x7fffec265380, memory=0x7fffecb33580)
    at vktrace/vktrace_layer/vktrace_lib_trace.cpp:449
(gdb) up
...
#5  0x00007ffff1fe808d in vkFlushMappedMemoryRangesWithoutAPICall (device=0x7fffec265380, memoryRangeCount=<optimized out>, 
    pMemoryRanges=<optimized out>) at vktrace/vktrace_layer/vktrace_lib_pageguard.cpp:400
400	                vktrace_add_buffer_to_trace_packet(pHeader, (void**)&(pPacket->ppData[iter]), OPTPackageSizeTemp, pOPTDataTemp);
(gdb) info locals
pOPTDataTemp = <optimized out>
pOPTMemoryTemp = 0x7fffeca8ec50
OPTPackageSizeTemp = 1346
pRange = 0x7ffff363df80
pHeader = 0x7fffee148f40
rangesSize = <optimized out>
dataSize = <optimized out>
iter = 0
pPacket = <optimized out>
ppPackageData = 0x7fffeca5c480
ppTmpData = <optimized out>

```
=> 1346 & 3 = 2 (instead of zero).

(For proprietary GfxBench v5 pre-release version.  It uses 16-bit depth and buffers.)

**Comment by davidlunarg** [comment]
Fixed in ea66ed5b27b48b54e114b13208429ececf74aed6
