### ISSUE TITLE
`accelerationStructureCaptureReplayDescriptorDataSize` breaks the Vulkan Profile Generator

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [LunarG/VulkanTools#1858]
Hi, the following Nvidia and AMD reports (both processed separately) break the Python script

[profiles.zip](https://github.com/LunarG/VulkanTools/files/12402451/profiles.zip)

Here's the backtrack
```
Traceback (most recent call last):
  File "gen_profiles_file.py", line 793, in <module>
    profile_merger.merge(jsons, profiles, profile_names, args.output_path, args.output_profile, args.profile_label, args.profile_desc, args.profile_api_version, profile_stage, profile_date, args.mode)
  File "gen_profiles_file.py", line 45, in merge
    merged['capabilities'] = self.merge_capabilities(jsons, profile_names, self.api_version)
  File "gen_profiles_file.py", line 132, in merge_capabilities
    self.add_members(merged_properties[property], capability['properties'][property], property)
  File "gen_profiles_file.py", line 408, in add_members
    xmlmember = self.registry.structs[property].members[member]
KeyError: 'accelerationStructureCaptureReplayDescriptorDataSize'
```

~~Should I be using a `vk.xml`  that is higher version than the reports?~~

The member is in the 1.3.250.1 SDK's provided vk.XML

**Comment by KarenGhavam-lunarG** [comment]
I think this issue should be in the [Vulkan-Profiles](https://github.com/KhronosGroup/Vulkan-Profiles) repository?

**Comment by devshgraphicsprogramming** [comment]
ok thanks
